In [2]:
import numpy as np

In [3]:
arr=np.array([10,20,30,40,50])
print(arr)

[10 20 30 40 50]


it looks similar to list then why do we need numpy
why because
it is faster,memory efficient,optimized,large scale

In [4]:
print(type(arr))

<class 'numpy.ndarray'>


In [6]:
my_list=[1,2,3,4]
my_array=np.array([1,2,3,4])
print(my_list)
print(my_array)

[1, 2, 3, 4]
[1 2 3 4]


In [7]:
print(my_list*2)

[1, 2, 3, 4, 1, 2, 3, 4]


In [8]:
print(my_array*2)

[2 4 6 8]


1D ARRAY

In [12]:
arr1=np.array([5,10,15,20,25])
print(arr1)

[ 5 10 15 20 25]


temp,student marks,stock prices

In [13]:
print(arr1.ndim)

1


In [14]:
print(arr1.shape)

(5,)


it means that one row containing 5 elements

In [15]:
arr2=np.array([
    [1,2,3],
    [4,5,6]])
print(arr2)

[[1 2 3]
 [4 5 6]]


this is 2D array and its similar to matrices.excel tables

In [16]:
print(arr2.ndim)

2


In [17]:
print(arr2.shape)

(2, 3)


here we have 2 rows and 3 columns

In [18]:
print(arr2.shape)

(2, 3)


In [21]:
arr3=np.array([
    [1,2],
    [3,4],
    [5,6]])
print(arr3)

[[1 2]
 [3 4]
 [5 6]]


In [22]:
arr=np.array([10,20,30,40,50])

In [23]:
print(arr)

[10 20 30 40 50]


In [24]:
print(arr[0])

10


from left to right is positive index and from right to left its negtive indexing in python always starts from zero

In [25]:
print(arr[1])
print(arr[2])
print(arr[3])


20
30
40


In [27]:
print(arr[-1])

50


In [30]:
print(arr[-2])
print(arr[-3])


40
30


suppose sensor latest reading is always at the end
in order to access it you can use neg index

In [33]:
arr2=np.array([
    [1,2,3],
    [4,5,6]
])

In [34]:
print(arr2)

[[1 2 3]
 [4 5 6]]


In [35]:
print(arr2[0,0])

1


In [36]:
print(arr2[1,2])

6


In [37]:
print(arr2[1,0])

4


In [38]:
print(arr2[5,6])

IndexError: index 5 is out of bounds for axis 0 with size 2

In [39]:
arr2=np.array([
    [1,2,3],
    [4,5,6],
    [10,11,12],
    [13,14,15]
])

In [40]:
print(arr2)

[[ 1  2  3]
 [ 4  5  6]
 [10 11 12]
 [13 14 15]]


In [42]:
print(arr2[3,2])

15


In [43]:
arr=np.array([10,20,30,40,50,60,70,80])
print(arr)

[10 20 30 40 50 60 70 80]


In [45]:
print(arr[2:5])

[30 40 50]


start is always included
and end is always excluded

In [46]:
print(arr[:4])

[10 20 30 40]


In [47]:
print(arr[2:])

[30 40 50 60 70 80]


In [51]:
print(arr[::1])

[10 20 30 40 50 60 70 80]


what if the step size is negative

In [52]:
print(arr[::-1])

[80 70 60 50 40 30 20 10]


selecting recent stock prices  extractibg image portions filtering sensor windows

In [53]:
arr2=np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
print(arr2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [54]:
print(arr2[0,:])

[1 2 3]


In [56]:
print(arr2[:,2])

[3 6 9]


In [57]:
print(arr2[0:2,0:2])

[[1 2]
 [4 5]]


in image processing cropping images uses slicing

In [58]:
arr=np.array([1,2,3,4,5,-1,-3])
print(arr[1:4])

[2 3 4]


In [59]:
print(arr[::-1])

[-3 -1  5  4  3  2  1]


In [60]:
print(arr[::2])

[ 1  3  5 -3]


In [70]:
arr=np.array([1,2,3,4,5,-1,8,9])
print(arr)

[ 1  2  3  4  5 -1  8  9]


In [73]:
reshaped=arr.reshape(4,2)
print(reshaped)

[[ 1  2]
 [ 3  4]
 [ 5 -1]
 [ 8  9]]


total elements must remain same

In [75]:
print(arr.reshape(4,2))

[[ 1  2]
 [ 3  4]
 [ 5 -1]
 [ 8  9]]


reshaping is used in ml dl image processing and signal processing

suppose there is some sensor data comes cont.. we may reshape it into matrix form for analysis

In [76]:
print(arr.reshape(2,-1))

[[ 1  2  3  4]
 [ 5 -1  8  9]]


-1 means numpy will automatically calculates columns

In [77]:
print(arr.reshape(-1,2))

[[ 1  2]
 [ 3  4]
 [ 5 -1]
 [ 8  9]]


numpy is smart enough to calculate dimensions automatically

flattening (used to convert multi dimensional arrays into 1D)

In [78]:
arr2=np.array([
    [1,2,3],
    [4,5,6]
])
print(arr2)

[[1 2 3]
 [4 5 6]]


In [80]:
flat=arr2.flatten()
print(flat)

[1 2 3 4 5 6]


we use this in preprocessing(data cleaning),data feeding,feature extraction

In [82]:
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15])
print(arr.reshape(5,3))

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]]


In [83]:
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15])

In [84]:
print(arr+10)

[11 12 13 14 15 16 17 18 19 20 21 22 23 24 25]


this automatic expansion of values is called as broadcasting

In [85]:
print(arr*10)

[ 10  20  30  40  50  60  70  80  90 100 110 120 130 140 150]


when we want to increase all sensor values    scaling image brightness

In [86]:
a=np.array([1,2,3])
b=np.array([10,20,30])
print(a+b)

[11 22 33]


In [87]:
print(a*b)

[10 40 90]


when we want to achieve signal multiplication we do this

In [88]:
arr2=np.array([
    [1,2,3],
    [4,5,6]])
print(arr2+10)

[[11 12 13]
 [14 15 16]]


In [93]:
arr=np.arange(10,10000000)
print(arr*87)

[      870       957      1044 ... 869999739 869999826 869999913]


In [94]:
arr[87654]

87664

In [95]:
a=np.array([1,2,3,4,5,6])
print(a+10)

[11 12 13 14 15 16]


In [96]:
print(a-10)


[-9 -8 -7 -6 -5 -4]


In [97]:
print(a/10)


[0.1 0.2 0.3 0.4 0.5 0.6]


In [103]:
print(a**2
     )

[ 1  4  9 16 25 36]


this we will use when you want to scale sensor values,normalization,signal amplification

numpy is mainly used for mathematic calc and efficient cal's

statistical operations:
we slowly move towards data analytics side
in data analytics statistics is everywhere!!!  why?????

In [112]:
marks=np.array([150,70,88,817,90,10])
print(marks)

[150  70  88 817  90  10]


In [113]:
print(np.mean(marks))

204.16666666666666


In [114]:
print(np.median(marks))

89.0


In [115]:
print(np.max(marks))
print(np.min(marks))

817
10


In [116]:
print(np.sum(marks))

1225


standard deviation

In [117]:
print(np.std(marks))

277.10672833565206


std tells you how spread out the data is

high deviation: values vary a lot difference is more
low deviation: values are closer and less difference

we use this std in stock market fluctuations signal variations sensor errors....

In [126]:
random_arr=np.random.randint(1,100,10)


In [127]:
random_arr

array([40, 81, 24, 54, 16, 26, 51, 78, 28, 76])

to generate random values in an array we use this randint

In [129]:
print(np.random.rand(5))

[0.88007797 0.56450997 0.91166106 0.50249012 0.06772192]


random decimal numbers between 0 and 1

training ai model,simulations,gaming,cybersecurity

In [130]:
print(np.zeros((3,3)))

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


a 3x3 matrix filled with zeros

In [131]:
print(np.ones((2,4)))

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


a 2x4 matrix filled with all ones

there are commonly used in ml initialization

In [132]:
print(np.eye(4))

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


here the diagonals elements becomes 1

linear algebra transformations ml maths

In [134]:
arr=np.array([5,13,17])
print(arr*2)

[10 26 34]


In [135]:
print(np.mean(arr))

11.666666666666666


In [137]:
a=np.array([1,2,3])
b=np.array([1,2,4])
print(a+b)

[2 4 7]


In [139]:
arr=np.array([1,2,3,4])
print(arr.reshape(2,2))

[[1 2]
 [3 4]]


In [140]:
sensor_data=np.array([23,25,26,27,28,28,29,30])
print(sensor_data)

[23 25 26 27 28 28 29 30]


In [141]:
print("average",np.mean(sensor_data))
print("maximum",np.max(sensor_data))
print("minimum",np.min(sensor_data))

average 27.0
maximum 30
minimum 23


In [142]:
sensor_data=np.append(sensor_data,100)
print(sensor_data)

[ 23  25  26  27  28  28  29  30 100]


outlier??? and outlier identification

if there is an outlier that might cause overheating machine failure abnormal behaviour

In [143]:
import numpy as np

In [144]:
student_names=np.array([
    "ajay","charishma","sruthi","prranava","ramya","sujith","charith","gayathri"])

In [145]:
marks=np.array([78,99,98,60,55,68,72,87])

In [153]:
attendance=np.array([78,77,65,45,39,55,77,98])

print("------student analytics system-------")
print("\n student names")
print(student_names)

print("\n marks")
print(marks)
print("\nattendance")
print(attendace)


In [150]:
print("\n--------basic analytics-----")
print("average marks:",np.mean(marks))
print("highest marks:",np.max(marks))
print("lowest marks:",np.min(marks))


--------basic analytics-----
average marks: 77.125
highest marks: 99
lowest marks: 55


In [151]:
highest_marks=np.max(marks)
highest_index=np.argmax(marks)
topper_name=student_names[highest_index]
print("highest marks:",highest_marks)
print("topper name:",topper_name)

highest marks: 99
topper name: charishma


argmax will give you the index position of maximum value

find out the person name with highest attendance

In [155]:
highest_att=np.max(attendance)
highest_index=np.argmax(attendance)
high_attendance=student_names[highest_index]
print("highest attendance:",highest_att)
print("topper name:",high_attendance)

highest attendance: 98
topper name: gayathri


find out who got the lowest marks and attendance

In [156]:
lowest_att=np.min(attendance)
lowest_index=np.argmin(attendance)
low_attendance=student_names[lowest_index]
print("lowest attendance:",lowest_att)
print("low attendance name:",low_attendance)

lowest attendance: 39
low attendance name: ramya


In [157]:
lowest_marks=np.min(marks)
lowest_index=np.argmin(marks)
lowestmarks_name=student_names[lowest_index]
print("lowest marks:",lowest_marks)
print("lowest marks name:",lowestmarks_name)

lowest marks: 55
lowest marks name: ramya


In [159]:
import numpy as np 
house_names=np.array([
    "house A",
    "house B",
    "house C",
    "house D",
    "house E",
    "house F",
    "house G",
    "house H"
])

In [160]:
electricity_units=np.array([
    120,125,180,122,290,300,400])


In [161]:
print("___smart eletricity analysis system______")
print("\n house names")
print(house_names)

___smart eletricity analysis system______

 house names
['house A' 'house B' 'house C' 'house D' 'house E' 'house F' 'house G'
 'house H']


In [167]:
print("_____basic analytics___")
print("average consumption",np.mean(electricity_units))
print("maximum consumption",np.max(electricity_units))
print("minimum consumption",np.min(electricity_units))
print("total electricity consumption",np.sum(electricity_units))
print("\n highest consumption house")
highest_index=np.argmax(electricity_units)
highest_house=house_names[highest_index]
highest_units=electricity_units[highest_index]
print("house name",highest_house)
print("units consumed",highest_units)

_____basic analytics___
average consumption 219.57142857142858
maximum consumption 400
minimum consumption 120
total electricity consumption 1537

 highest consumption house
house name house G
units consumed 400


In [169]:
a=10
b=40
c=20
d=25
print(f"the value of a is {a} and the value of b is {b}")

the value of a is 10 and the value of b is 40


normally in python if we want to process multiple values we use loops
but numpy can process entire arrays directly without loops 
that is called as vectorization

In [170]:
numbers=[1,2,3,4,5]
result=[]
for i in numbers:
    result.append(i*2)
print(result)

[2, 4, 6, 8, 10]


In [171]:
arr=np.array([1,2,3,4,5])
result=arr*2
print(result)

[ 2  4  6  8 10]


no loops but still all elements are processed

numpy internally uses optmimized low level implementations
fast clean memory efficient

In [172]:
large_array=np.arange(1,1000000)
result=large_array*5
print(result)

[      5      10      15 ... 4999985 4999990 4999995]


In [173]:
sensor_data=np.array([
    10,20,30,40,50,
    60,70,80,90,100])
print("original sensor data")
print(sensor_data)

original sensor data
[ 10  20  30  40  50  60  70  80  90 100]


In [174]:
print("\n amplified sensor values")
print(sensor_data*1.5)


 amplified sensor values
[ 15.  30.  45.  60.  75.  90. 105. 120. 135. 150.]


In [175]:
print("\n increased temparature")
print(sensor_data+10)


 increased temparature
[ 20  30  40  50  60  70  80  90 100 110]


In [177]:
print("\n power consumption")
print(sensor_data**2)


 power consumption
[  100   400   900  1600  2500  3600  4900  6400  8100 10000]
